### ISSUE TITLE
Bug: No drawer view found with gravity LEFT

### ISSUE THREAD

**Issue by viezel** [trendier-ai/Ti.DrawerLayout#17]
First of all - great great drawer you got here! Mad props from me !

It seems like you did not instantiate the drawer correctly. I get the following stack trace, when trying to toggle the left drawer. (version 1.1.1)

```
[ERROR] :  TiApplication: (main) [2365,7494] Sending event: exception on thread: main msg:java.lang.IllegalArgumentException: No drawer view found with gravity LEFT; Titanium 3.3.0,2014/05/22 13:33,0d36b26
[ERROR] :  TiApplication: java.lang.IllegalArgumentException: No drawer view found with gravity LEFT
[ERROR] :  TiApplication:   at android.support.v4.widget.DrawerLayout.openDrawer(DrawerLayout.java:1099)
[ERROR] :  TiApplication:   at com.tripvi.drawerlayout.Drawer.openLeftDrawer(Drawer.java:191)
[ERROR] :  TiApplication:   at com.tripvi.drawerlayout.Drawer.toggleLeftDrawer(Drawer.java:187)
[ERROR] :  TiApplication:   at com.tripvi.drawerlayout.DrawerProxy.handleToggleLeftView(DrawerProxy.java:86)
[ERROR] :  TiApplication:   at com.tripvi.drawerlayout.DrawerProxy.handleMessage(DrawerProxy.java:56)
[ERROR] :  TiApplication:   at android.os.Handler.dispatchMessage(Handler.java:95)
[ERROR] :  TiApplication:   at android.os.Looper.loop(Looper.java:137)
[ERROR] :  TiApplication:   at android.app.ActivityThread.main(ActivityThread.java:5039)
[ERROR] :  TiApplication:   at java.lang.reflect.Method.invokeNative(Native Method)
[ERROR] :  TiApplication:   at java.lang.reflect.Method.invoke(Method.java:511)
[ERROR] :  TiApplication:   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
[ERROR] :  TiApplication:   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:560)
[ERROR] :  TiApplication:   at dalvik.system.Nativ
```

Hope it can be solved.
Cheers. 
Mads

**Comment by metacortex** [comment]
can you post some test code?

**Comment by viezel** [comment]
I just used your example code from the module.

**Comment by metacortex** [comment]
I can't reproduce the error.
Would you provide more info about os, version, environments?

**Comment by jonathanrcarter** [comment]
Hi

did you resolve this as I am getting exactly the same error?

**Comment by pratikbutani** [comment]
Post your XML of main activity.

**Comment by pratikbutani** [comment]
http://stackoverflow.com/a/28403050/1318946
