### ISSUE TITLE
Using Ti.DrawerLayout with TabGroup

### ISSUE THREAD

**Issue by asterixcapri** [trendier-ai/Ti.DrawerLayout#19]
Hi, I'm trying to use Ti.DrawerLayout in an app with tabGroup. If I insert just one DrawerLayout everything is fine, but it creates problems with more than one.

Here is my example code:

```
var TiDrawerLayout = require('com.tripvi.drawerlayout');

var tabGroup = Ti.UI.createTabGroup();

tabGroup.addTab(createTab1());
tabGroup.addTab(createTab2());

tabGroup.open();

function createTab1()
{
    var tab = Ti.UI.createTab({ title: "Tab 1" });
    var win = Ti.UI.createWindow();

    var view = Ti.UI.createView();
    view.add(Ti.UI.createLabel({ text: "First", color: "black" }));

    var drawer = TiDrawerLayout.createDrawer({
        leftWindow: createMenuTableView(),
        centerWindow: view,
        leftDrawerWidth: "280dp",
        width: Ti.UI.FILL,
        height: Ti.UI.FILL,
    });

    win.add(drawer);
    tab.window = win;

    return tab;
}

function createMenuTableView()
{
    return Ti.UI.createTableView({
        backgroundColor: "#ddd",
        data: [
            { title: "menu A" },
            { title: "menu B" },
            { title: "menu C" },
            { title: "menu D" }
        ]
    });
}

function createTab2()
{
    var tab = Ti.UI.createTab({ title: "Tab 2" });
    var win = Ti.UI.createWindow();

    var view = Ti.UI.createView();
    view.add(Ti.UI.createLabel({ text: "Second", color: "black" }));

    var drawer = TiDrawerLayout.createDrawer({
        leftWindow: createMenuTableView(),
        centerWindow: view,
        leftDrawerWidth: "280dp",
        width: Ti.UI.FILL,
        height: Ti.UI.FILL,
    });

    win.add(drawer);
    tab.window = win;

    return tab;
}
```

When I tap on the second tab, the content of it is shown on the first tab. Is there a solution to this problem?

Thanks
Alex

**Comment by timanrebel** [comment]
@manumaticx would you have any idea how to solve this? When I add a TabGroup to the center view it crashes as well. I understand why, a TabGroup is also a Window in Titanium. Maybe we should use a couple of Views with a ViewPager and the DrawerLayout instead

```
10-19 16:30:29.783: E/AndroidRuntime(9558): java.lang.RuntimeException: Unable to start activity ComponentInfo{eu.rebelcorp.rebelapp/org.appcelerator.titanium.TiActivity}: java.lang.IllegalStateException: Windows are created during open
10-19 16:30:29.783: E/AndroidRuntime(9558):     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2195)
10-19 16:30:29.783: E/AndroidRuntime(9558):     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2245)
10-19 16:30:29.783: E/AndroidRuntime(9558):     at android.app.ActivityThread.access$800(ActivityThread.java:135)
10-19 16:30:29.783: E/AndroidRuntime(9558):     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1196)
10-19 16:30:29.783: E/AndroidRuntime(9558):     at android.os.Handler.dispatchMessage(Handler.java:102)
10-19 16:30:29.783: E/AndroidRuntime(9558):     at android.os.Looper.loop(Looper.java:136)
10-19 16:30:29.783: E/AndroidRuntime(9558):     at android.app.ActivityThread.main(ActivityThread.java:5017)
10-19 16:30:29.783: E/AndroidRuntime(9558):     at java.lang.reflect.Method.invokeNative(Native Method)
10-19 16:30:29.783: E/AndroidRuntime(9558):     at java.lang.reflect.Method.invoke(Method.java:515)
10-19 16:30:29.783: E/AndroidRuntime(9558):     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779)
10-19 16:30:29.783: E/AndroidRuntime(9558):     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595)
10-19 16:30:29.783: E/AndroidRuntime(9558):     at dalvik.system.NativeStart.main(Native Method)
10-19 16:30:29.783: E/AndroidRuntime(9558): Caused by: java.lang.IllegalStateException: Windows are created during open
10-19 16:30:29.783: E/AndroidRuntime(9558):     at org.appcelerator.titanium.proxy.TiWindowProxy.createView(TiWindowProxy.java:79)
10-19 16:30:29.783: E/AndroidRuntime(9558):     at org.appcelerator.titanium.proxy.TiViewProxy.handleGetView(TiViewProxy.java:483)
10-19 16:30:29.783: E/AndroidRuntime(9558):     at org.appcelerator.titanium.proxy.TiViewProxy.getOrCreateView(TiViewProxy.java:469)
10-19 16:30:29.783: E/AndroidRuntime(9558):     at com.tripvi.drawerlayout.Drawer.replaceCenterView(Drawer.java:275)
10-19 16:30:29.783: E/AndroidRuntime(9558):     at com.tripvi.drawerlayout.Drawer.processProperties(Drawer.java:353)
10-19 16:30:29.783: E/AndroidRuntime(9558):     at org.appcelerator.kroll.KrollProxy.setModelListener(KrollProxy.java:1185)
10-19 16:30:29.783: E/AndroidRuntime(9558):     at org.appcelerator.titanium.proxy.TiViewProxy.realizeViews(TiViewProxy.java:500)
10-19 16:30:29.783: E/AndroidRuntime(9558):     at org.appcelerator.titanium.proxy.TiViewProxy.handleGetView(TiViewProxy.java:491)
10-19 16:30:29.783: E/AndroidRuntime(9558):     at org.appcelerator.titanium.proxy.TiViewProxy.getOrCreateView(TiViewProxy.java:469)
10-19 16:30:29.783: E/AndroidRuntime(9558):     at org.appcelerator.titanium.proxy.TiViewProxy.realizeViews(TiViewProxy.java:507)
10-19 16:30:29.783: E/AndroidRuntime(9558):     at org.appcelerator.titanium.proxy.TiViewProxy.handleGetView(TiViewProxy.java:491)
10-19 16:30:29.783: E/AndroidRuntime(9558):     at org.appcelerator.titanium.proxy.TiViewProxy.getOrCreateView(TiViewProxy.java:469)
10-19 16:30:29.783: E/AndroidRuntime(9558):     at org.appcelerator.titanium.proxy.TiViewProxy.handleAdd(TiViewProxy.java:670)
10-19 16:30:29.783: E/AndroidRuntime(9558):     at org.appcelerator.titanium.proxy.TiViewProxy.add(TiViewProxy.java:564)
10-19 16:30:29.783: E/AndroidRuntime(9558):     at ti.modules.titanium.ui.WindowProxy.windowCreated(WindowProxy.java:232)
10-19 16:30:29.783: E/AndroidRuntime(9558):     at org.appcelerator.titanium.TiActivityWindows.windowCreated(TiActivityWindows.java:32)
10-19 16:30:29.783: E/AndroidRuntime(9558):     at org.appcelerator.titanium.TiBaseActivity.windowCreated(TiBaseActivity.java:442)
10-19 16:30:29.783: E/AndroidRuntime(9558):     at org.appcelerator.titanium.TiBaseActivity.onCreate(TiBaseActivity.java:524)
10-19 16:30:29.783: E/AndroidRuntime(9558):     at org.appcelerator.titanium.TiActivity.onCreate(TiActivity.java:18)
10-19 16:30:29.783: E/AndroidRuntime(9558):     at android.app.Activity.performCreate(Activity.java:5231)
10-19 16:30:29.783: E/AndroidRuntime(9558):     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087)
10-19 16:30:29.783: E/AndroidRuntime(9558):     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2159)
```

**Comment by manumaticx** [comment]
@timanrebel Technically, it would be possible but this is not supported by this module. But I won't implement tab group support for this because it's a kind of anti-pattern to use the Navigation drawer with Actionbar Tabs. Here's a [quote](https://plus.google.com/u/0/+DavidTaSmoochibi/posts/8dWEkFcbTFX) from Roman Nurik:

_"You shouldn't use navigation drawers with action bar tabs. If you're aiming for a UI similar to that of Google Play Music, you should implement tabs manually (and beware of how this looks on tablet—you don't want full-width tab bars on tablets)."_

A view-based solution is probably the best answer to this (as you already proposed) - I've never tried this but I would use a view pager like [net.bajawa.pager](https://marketplace.appcelerator.com/apps/2228#!overview) or some custom tabgroup.

**Comment by timanrebel** [comment]
I totally agree that you either have to choose tabs or a nav drawer. In my case I wanted to use this module to display notifications in a right nav drawer, in the same way as Google+ does. But maybe I rewrite the app to use a ViewPager (quite a bit of work), or use something else for the notifications.

Thanks!
