### ISSUE TITLE
Use TiDrawerLayout with viewpager

### ISSUE THREAD

**Issue by ankesh27** [trendier-ai/Ti.DrawerLayout#26]
Hello,

Any Idea of how do I use TiDrawerLayout with  viewpager(https://github.com/dreamlearn/viewpager).

I am not sure what will be the centerView..

Help appreciated..

Cheers!

**Comment by ankesh27** [comment]
Error says 
[ERROR] :  TiApplication: (main) [230,163640] Sending event: exception on thread: main msg:java.lang.RuntimeException: Unable to start activity ComponentInfo{com.mydala/org.appcelerator.titanium.TiActivity}: java.lang.IllegalStateException: The specified child already has a parent. You must call removeView() on the child's parent first.; Titanium 3.3.0,2014/05/19 17:41,0f50581
[ERROR] :  TiApplication: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.mydala/org.appcelerator.titanium.TiActivity}: java.lang.IllegalStateException: The specified child already has a parent. You must call removeView() on the child's parent first.

**Comment by ankesh27** [comment]
My Bad, Sorry. I have resolved it, was making silly mistake by adding center view twice(One on TiDrawerLayout and secondly on main window).

Cheers!
Ankesh

**Comment by ricardoalcocer** [comment]
@ankesh27, how were you able to add the ViewPager to the DrawerLayout?  Are you configuring the "tabs" and adding them as the centerView of the DrawerLayout module?  I'm trying but getting errors.

**Comment by ankesh27** [comment]
@ricardoalcocer Can you please share your error code. I am out somewhere, Will share the sample code Soon.

**Comment by ankesh27** [comment]
@ricardoalcocer  did you find the solution or shall i share the code ?

**Comment by ricardoalcocer** [comment]
Hi, no I haven't.  Last time I tried was having issues (don't remember exact message).  If you could share a working sample, that would be great.  Did you add the ViewPager straight to the centerView?

**Comment by ankesh27** [comment]
@ricardoalcocer

```
var Map_Win = Titanium.UI.currentWindow;
var main = Titanium.UI.createView({
    height : '100%',
    width : '100%',
    backgroundColor : '#ffffff',
    top : 0,
    left : 0,
    zIndex : 10
});
var TiDrawerLayout = require('com.tripvi.drawerlayout');
var mainPageTableMenuView = TiDrawerLayout.createDrawer({
    leftView : tableViewLeftMenu,
    //rightView: rv,
    centerView : main,
    leftDrawerWidth : l(240),
    width : Ti.UI.FILL,
    height : Ti.UI.FILL,
    top : 0
});
var TabsModule = require('com.navid.tabs');
var tabs = TabsModule.createPagerTabs({
    current : 1,
    top : 40,
    tab : {
        backgroundColor : "#efefef",
        alignment : TabsModule.ALIGNMENT_LEFT,
        indicatorColor : "#7f7d7e",
        color : "#000000",
        underlineColor : "#7f7d7e",
        font : {
            size : (12),
            color : "#ffffff",
            colorSelected : "#ffffff",
            bold : false
        },
        padding : 30,
        dividerPadding : 5
    },
    views : [{
        title : "Home ",
        view : homeView
    },{
        title : "Tab 1 ",
        view : tab1view
    }, {
        title : "Tab2 ",
        view : tab2view
    }, {
        title : "Tab 3 ",
        view : tab3view
    }]
});

main.add(tabs);
Map_Win.add(mainPageTableMenuView);
```

//// END OF CODE
PS : tab1view, tab2view resp are the views you want to show on tabs..

Please ask in case of any question/concern

Cheers!
Anki

**Comment by ardiwine** [comment]
Hi @ankesh27 

I tried running your sample code with some modification due to missing views etc. but I still could not manage to get it to work 

here's the error looks like

```
WARN] :   ResourceType: No package identifier when getting name for resource number 0x000022b9
[WARN] :   dalvikvm: threadid=1: thread exiting with uncaught exception (group=0xa4d51b20)
[ERROR] :  TiApplication: (main) [928,928] Sending event: exception on thread: main msg:android.content.res.Resources$NotFoundException: Unable to find resource ID #0x22b9; Titanium 3.4.0,2014/09/25 16:42,b54c467
[ERROR] :  TiApplication: android.content.res.Resources$NotFoundException: Unable to find resource ID #0x22b9
[ERROR] :  TiApplication:   at android.content.res.Resources.getResourceName(Resources.java:1773)
[ERROR] :  TiApplication:   at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:930)
[ERROR] :  TiApplication:   at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1115)
[ERROR] :  TiApplication:   at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:682)
[ERROR] :  TiApplication:   at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1478)
[ERROR] :  TiApplication:   at android.support.v4.app.FragmentManagerImpl.executePendingTransactions(FragmentManager.java:478)
[ERROR] :  TiApplication:   at android.support.v4.app.FragmentStatePagerAdapter.finishUpdate(FragmentStatePagerAdapter.java:163)
[ERROR] :  TiApplication:   at android.support.v4.view.ViewPager.populate(ViewPager.java:1068)
[ERROR] :  TiApplication:   at android.support.v4.view.ViewPager.populate(ViewPager.java:914)
[ERROR] :  TiApplication:   at android.support.v4.view.ViewPager.onMeasure(ViewPager.java:1436)
[ERROR] :  TiApplication:   at android.view.View.measure(View.java:16497)
[ERROR] :  TiApplication:   at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5125)
[ERROR] :  TiApplication:   at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1404)
[ERROR] :  TiApplication:   at android.widget.LinearLayout.measureVertical(LinearLayout.java:695)
[ERROR] :  TiApplication:   at android.widget.LinearLayout.onMeasure(LinearLayout.java:588)
[ERROR] :  TiApplication:   at android.view.View.measure(View.java:16497)
[ERROR] :  TiApplication:   at org.appcelerator.titanium.view.TiCompositeLayout.constrainChild(TiCompositeLayout.java:398)
[ERROR] :  TiApplication:   at org.appcelerator.titanium.view.TiCompositeLayout.onMeasure(TiCompositeLayout.java:278)
[ERROR] :  TiApplication:   at android.view.View.measure(View.java:16497)
[ERROR] :  TiApplication:   at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5125)
[ERROR] :  TiApplication:   at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
[ERROR] :  TiApplication:   at android.view.View.measure(View.java:16497)
[ERROR] :  TiApplication:   at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5125)
[ERROR] :  TiApplication:   at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
[ERROR] :  TiApplication:   at android.view.View.measure(View.java:16497)
[ERROR] :  TiApplication:   at android.support.v4.widget.DrawerLayout.onMeasure(DrawerLayout.java:704)
[ERROR] :  TiApplication:   at android.view.View.measure(View.java:16497)
[ERROR] :  TiApplication:   at org.appcelerator.titanium.view.TiCompositeLayout.constrainChild(TiCompositeLayout.java:398)
[ERROR] :  TiApplication:   at org.appcelerator.titanium.view.TiCompositeLayout.onMeasure(TiCompositeLayout.java:278)
[ERROR] :  TiApplication:   at android.view.View.measure(View.java:16497)
[ERROR] :  TiApplication:   at org.appcelerator.titanium.view.TiCompositeLayout.constrainChild(TiCompositeLayout.java:398)
[ERROR] :  TiApplication:   at org.appcelerator.titanium.view.TiCompositeLayout.onMeasure(TiCompositeLayout.java:278)
[ERROR] :  TiApplication:   at android.view.View.measure(View.java:16497)
[ERROR] :  TiApplication:   at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5125)
[ERROR] :  TiApplication:   at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
[ERROR] :  TiApplication:   at android.view.View.measure(View.java:16497)
[ERROR] :  TiApplication:   at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5125)
[ERROR] :  TiApplication:   at com.android.internal.widget.ActionBarOverlayLayou
[ERROR] :  TiApplication:   at android.view.View.measure(View.java:16497)
[ERROR] :  TiApplication:   at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5125)
[ERROR] :  TiApplication:   at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
[ERROR] :  TiApplication:   at com.android.internal.policy.impl.PhoneWindow$DecorView.onMeasure(PhoneWindow.java:2291)
[ERROR] :  TiApplication:   at android.view.View.measure(View.java:16497)
[ERROR] :  TiApplication:   at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:1916)
[ERROR] :  TiApplication:   at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1113)
[ERROR] :  TiApplication:   at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1295)
[ERROR] :  TiApplication:   at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1000)
[ERROR] :  TiApplication:   at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5670)
[ERROR] :  TiApplication:   at android.view.Choreographer$CallbackRecord.run(Choreographer.java:761)
[ERROR] :  TiApplication:   at android.view.Choreographer.doCallbacks(Choreographer.java:574)
[ERROR] :  TiApplication:   at android.view.Choreographer.doFrame(Choreographer.java:544)
[ERROR] :  TiApplication:   at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:747)
[ERROR] :  TiApplication:   at android.os.Handler.handleCallback(Handler.java:733)
[ERROR] :  TiApplication:   at android.os.Handler.dispatch
[INFO] :   Process: Sending signal. PID: 15271 SIG: 9
```

**Comment by mopx** [comment]
Hi @ardiwine did you solve your problem? I'm getting the same error.

**Comment by ricardoalcocer** [comment]
Guys, I suggest you follow and file issues in either the original repo at [https://github.com/Tripvi/Ti.DrawerLayout](https://github.com/Tripvi/Ti.DrawerLayout), or @manumaticx 's fork at [https://github.com/manumaticx/Ti.DrawerLayout](https://github.com/manumaticx/Ti.DrawerLayout) .  This repo has no activity.  Manuel's is ahead of Tripvi's.

**Comment by ardiwine** [comment]
@mopx I second @ricardoalcocer to check @manumaticx 's fork

**Comment by manumaticx** [comment]
@mopx Just to let you know, I've tested this a while ago but didn't came up with a solution on the Drawer side. I'm afraid there's a bug in the view pager module. I recommend you using the official titanium view pager implementation (Ti.UI.ScrollableView) - I have no problems with this within the Drawer.

**Comment by mopx** [comment]
@manumaticx I'll try doing that, thanks for taking the time to respond.

**Comment by ricardoalcocer** [comment]
And @manumaticx has a "work-in-progress" Alloy Widget to implement the Pager Title Strip at [https://github.com/manumaticx/pagingcontrol](https://github.com/manumaticx/pagingcontrol)
