### ISSUE TITLE
DrawerLayout must be measured with MeasureSpec.EXACTLY

### ISSUE THREAD

**Issue by timanrebel** [trendier-ai/Ti.DrawerLayout#36]
I'm trying to use the module on 3.3.0.GA on both Genymotion and a device, but keep getting the following error:

```
[ERROR] TiApplication: (main) [173,176] Sending event: exception on thread: main msg:java.lang.IllegalArgumentException: DrawerLayout must be measured with MeasureSpec.EXACTLY.; Titanium 3.3.0,2014/07/11 12:36,787cd39
[ERROR] TiApplication: java.lang.IllegalArgumentException: DrawerLayout must be measured with MeasureSpec.EXACTLY.
[ERROR] TiApplication:  at android.support.v4.widget.DrawerLayout.onMeasure(DrawerLayout.java:679)
[ERROR] TiApplication:  at android.view.View.measure(View.java:16831)
[ERROR] TiApplication:  at org.appcelerator.titanium.view.TiCompositeLayout.constrainChild(TiCompositeLayout.java:398)
[ERROR] TiApplication:  at org.appcelerator.titanium.view.TiCompositeLayout.onMeasure(TiCompositeLayout.java:278)
[ERROR] TiApplication:  at android.view.View.measure(View.java:16831)
[ERROR] TiApplication:  at org.appcelerator.titanium.view.TiCompositeLayout.constrainChild(TiCompositeLayout.java:398)
[ERROR] TiApplication:  at org.appcelerator.titanium.view.TiCompositeLayout.onMeasure(TiCompositeLayout.java:278)
[ERROR] TiApplication:  at android.view.View.measure(View.java:16831)
[ERROR] TiApplication:  at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5245)
[ERROR] TiApplication:  at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
[ERROR] TiApplication:  at android.view.View.measure(View.java:16831)
[ERROR] TiApplication:  at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5245)
[ERROR] TiApplication:  at com.android.internal.widget.ActionBarOverlayLayout.onMeasure(ActionBarOverlayLayout.java:302)
[ERROR] TiApplication:  at android.view.View.measure(View.java:16831)
[ERROR] TiApplication:  at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5245)
[ERROR] TiApplication:  at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
[ERROR] TiApplication:  at com.android.internal.policy.impl.PhoneWindow$DecorView.onMeasure(PhoneWindow.java:2586)
[ERROR] TiApplication:  at android.view.View.measure(View.java:16831)
[ERROR] TiApplication:  at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2189)
[ERROR] TiApplication:  at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1352)
[ERROR] TiApplication:  at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1535)
[ERROR] TiApplication:  at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1249)
[ERROR] TiApplication:  at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6364)
[ERROR] TiApplication:  at android.view.Choreographer$CallbackRecord.run(Choreographer.java:791)
[ERROR] TiApplication:  at android.view.Choreographer.doCallbacks(Choreographer.java:591)
[ERROR] TiApplication:  at android.view.Choreographer.doFrame(Choreographer.java:561)
[ERROR] TiApplication:  at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:777)
[ERROR] TiApplication:  at android.os.Handler.handleCallback(Handler.java:730)
[ERROR] TiApplication:  at android.os.Handler.dispatchMessage(Handler.java:92)
[ERROR] TiApplication:  at android.os.Looper.loop(Looper.java:176)
[ERROR] TiApplication:  at android.app.ActivityThread.main(ActivityThread.java:5419)
[ERROR] TiApplication:  at java.lang.reflect.Method.invokeNative(Native Method)
[ERROR] TiApplication:  at java.lang.reflect.Method.invoke(Method.java:525)
[ERROR] TiApplication:  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1046)
[ERROR] TiApplication:  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:862)
[ERROR] TiApplication:  at dalvik.system.NativeStart.main(Native Method)
```

Code I use:

```
var DrawerModule = require('com.tripvi.drawerlayout');

var navdrawer = DrawerModule.createDrawer({
    leftView: Ti.UI.createView({backgroundColor: 'red'}),
    centerView: Ti.UI.createView({backgroundColor: 'green'}),
    // leftDrawerWidth: "240px",
    // drawerIndicatorEnabled: true
});

var win = Ti.UI.createWindow({
    // navBarHidden: true
});
win.add(navdrawer);

win.open();
```

( I already stripped out everything that could cause the issue from my app)

Does anyone have a tip or a solution?

**Comment by timanrebel** [comment]
I use version 1.1.1 from gitt.io btw

**Comment by manumaticx** [comment]
Hi Timan, you should try replacing `leftDrawerWidth: "240px"` with `leftDrawerWidth: "240dp"`

**Comment by timanrebel** [comment]
Hi @manumaticx have tried 240, 240dp and 240px.

I have the same issue in another app, just added the demo code there as well..

**Comment by manumaticx** [comment]
@timanrebel ok, can you test if you get the same error with [version 1.1.5](https://github.com/manumaticx/Ti.DrawerLayout/blob/master/dist/com.tripvi.drawerlayout-android-1.1.5.zip) from my fork?

**Comment by timanrebel** [comment]
I had already tried that, but.. the code from your `example/app.js` works, so will debug why the error occurs and report back!

**Comment by timanrebel** [comment]
**Solution**

When creating the Drawer, width and height are mandatory. To fix this error make sure you add width and height:

```
DrawerModule.createDrawer({
    ...
    width: Ti.UI.FILL,
    height: Ti.UI.FILL
});
```

I had already forked this repo to improve the documentation in the README. Will add this to the demo code and do a PR

**Comment by timanrebel** [comment]
(and thanks for your quick help @manumaticx)

**Comment by manumaticx** [comment]
Good finding! I didn't know that. The Drawer should fall back to default values for width and height if they're not set - I'm trying to create a PR for that too!
