### ISSUE TITLE
App crashes when language of Android is changed

### ISSUE THREAD

**Issue by timanrebel** [trendier-ai/Ti.DrawerLayout#42]
When changes the language of Android, the app with DrawerLayout in it crashes with the following stack trace:

```
[ERROR] TiApplication: (main) [23280,83891] Sending event: exception on thread: main msg:java.lang.RuntimeException: Unable to start activity ComponentInfo{cxpmobile.backbase.com/org.appcelerator.titanium.TiActivity}: android.support.v4.app.Fragment$InstantiationException: Unable to instantiate fragment com.tripvi.drawerlayout.Drawer$ContentWrapperFragment: make sure class name exists, is public, and has an empty constructor that is public; Titanium 3.4.0,2014/09/22 13:57,541e19e
[ERROR] TiApplication: java.lang.RuntimeException: Unable to start activity ComponentInfo{cxpmobile.backbase.com/org.appcelerator.titanium.TiActivity}: android.support.v4.app.Fragment$InstantiationException: Unable to instantiate fragment com.tripvi.drawerlayout.Drawer$ContentWrapperFragment: make sure class name exists, is public, and has an empty constructor that is public
[ERROR] TiApplication:  at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2195)
[ERROR] TiApplication:  at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2245)
[ERROR] TiApplication:  at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:3738)
[ERROR] TiApplication:  at android.app.ActivityThread.access$900(ActivityThread.java:135)
[ERROR] TiApplication:  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1202)
[ERROR] TiApplication:  at android.os.Handler.dispatchMessage(Handler.java:102)
[ERROR] TiApplication:  at android.os.Looper.loop(Looper.java:136)
[ERROR] TiApplication:  at android.app.ActivityThread.main(ActivityThread.java:5017)
[ERROR] TiApplication:  at java.lang.reflect.Method.invokeNative(Native Method)
[ERROR] TiApplication:  at java.lang.reflect.Method.invoke(Method.java:515)
[ERROR] TiApplication:  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779)
[ERROR] TiApplication:  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595)
[ERROR] TiApplication:  at dalvik.system.NativeStart.main(Native Method)
[ERROR] TiApplication: Caused by: android.support.v4.app.Fragment$InstantiationException: Unable to instantiate fragment com.tripvi.drawerlayout.Drawer$ContentWrapperFragment: make sure class name exists, is public, and has an empty constructor that is public
[ERROR] TiApplication:  at android.support.v4.app.Fragment.instantiate(Fragment.java:413)
[ERROR] TiApplication:  at android.support.v4.app.FragmentState.instantiate(Fragment.java:97)
[ERROR] TiApplication:  at android.support.v4.app.FragmentManagerImpl.restoreAllState(FragmentManager.java:1801)
[ERROR] TiApplication:  at android.support.v4.app.FragmentActivity.onCreate(FragmentActivity.java:213)
[ERROR] TiApplication:  at android.support.v7.app.ActionBarActivity.onCreate(ActionBarActivity.java:97)
[ERROR] TiApplication:  at org.appcelerator.titanium.TiBaseActivity.onCreate(TiBaseActivity.java:516)
[ERROR] TiApplication:  at org.appcelerator.titanium.TiActivity.onCreate(TiActivity.java:18)
[ERROR] TiApplication:  at android.app.Activity.performCreate(Activity.java:5231)
[ERROR] TiApplication:  at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087)
[ERROR] TiApplication:  at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2159)
[ERROR] TiApplication:  ... 12 more
[ERROR] TiApplication: Caused by: java.lang.InstantiationException: can't instantiate class com.tripvi.drawerlayout.Drawer$ContentWrapperFragment; no empty constructor
[ERROR] TiApplication:  at java.lang.Class.newInstanceImpl(Native Method)
[ERROR] TiApplication:  at java.lang.Class.newInstance(Class.java:1208)
[ERROR] TiApplication:  at android.support.v4.app.Fragment.instantiate(Fragment.java:402)
```

**Comment by manumaticx** [comment]
Looks like the error in #22 
But I can reproduce this even with the bugfixed version.

**Comment by timanrebel** [comment]
That's weird, cause you would think that the empty constructor would fix that..

**Comment by timanrebel** [comment]
Do you still have it in 1.1.7 (your Fork)? Seems to be working here. Let me double check

**Comment by manumaticx** [comment]
I've checked it again with 1.1.7 - it crashes, but with another exception. I get:

```
09-26 14:31:01.984: E/AndroidRuntime(29249): FATAL EXCEPTION: main
09-26 14:31:01.984: E/AndroidRuntime(29249): Process: com.goyya.fde, PID: 29249
09-26 14:31:01.984: E/AndroidRuntime(29249): java.lang.RuntimeException: Unable to start activity ComponentInfo{com.goyya.fde/org.appcelerator.titanium.TiActivity}: java.lang.IllegalStateException: The specified child already has a parent. You must call removeView() on the child's parent first.
09-26 14:31:01.984: E/AndroidRuntime(29249):    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2184)
09-26 14:31:01.984: E/AndroidRuntime(29249):    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2233)
09-26 14:31:01.984: E/AndroidRuntime(29249):    at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:3724)
09-26 14:31:01.984: E/AndroidRuntime(29249):    at android.app.ActivityThread.access$900(ActivityThread.java:135)
09-26 14:31:01.984: E/AndroidRuntime(29249):    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1202)
09-26 14:31:01.984: E/AndroidRuntime(29249):    at android.os.Handler.dispatchMessage(Handler.java:102)
09-26 14:31:01.984: E/AndroidRuntime(29249):    at android.os.Looper.loop(Looper.java:136)
09-26 14:31:01.984: E/AndroidRuntime(29249):    at android.app.ActivityThread.main(ActivityThread.java:5001)
09-26 14:31:01.984: E/AndroidRuntime(29249):    at java.lang.reflect.Method.invokeNative(Native Method)
09-26 14:31:01.984: E/AndroidRuntime(29249):    at java.lang.reflect.Method.invoke(Method.java:515)
09-26 14:31:01.984: E/AndroidRuntime(29249):    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
09-26 14:31:01.984: E/AndroidRuntime(29249):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
09-26 14:31:01.984: E/AndroidRuntime(29249):    at dalvik.system.NativeStart.main(Native Method)
09-26 14:31:01.984: E/AndroidRuntime(29249): Caused by: java.lang.IllegalStateException: The specified child already has a parent. You must call removeView() on the child's parent first.
09-26 14:31:01.984: E/AndroidRuntime(29249):    at android.view.ViewGroup.addViewInner(ViewGroup.java:3562)
09-26 14:31:01.984: E/AndroidRuntime(29249):    at android.view.ViewGroup.addView(ViewGroup.java:3415)
09-26 14:31:01.984: E/AndroidRuntime(29249):    at android.view.ViewGroup.addView(ViewGroup.java:3360)
09-26 14:31:01.984: E/AndroidRuntime(29249):    at android.view.ViewGroup.addView(ViewGroup.java:3336)
09-26 14:31:01.984: E/AndroidRuntime(29249):    at com.tripvi.drawerlayout.Drawer.processProperties(Drawer.java:304)
09-26 14:31:01.984: E/AndroidRuntime(29249):    at org.appcelerator.kroll.KrollProxy.setModelListener(KrollProxy.java:1185)
09-26 14:31:01.984: E/AndroidRuntime(29249):    at org.appcelerator.titanium.proxy.TiViewProxy.realizeViews(TiViewProxy.java:500)
09-26 14:31:01.984: E/AndroidRuntime(29249):    at org.appcelerator.titanium.proxy.TiViewProxy.handleGetView(TiViewProxy.java:491)
09-26 14:31:01.984: E/AndroidRuntime(29249):    at org.appcelerator.titanium.proxy.TiViewProxy.getOrCreateView(TiViewProxy.java:469)
09-26 14:31:01.984: E/AndroidRuntime(29249):    at org.appcelerator.titanium.proxy.TiViewProxy.realizeViews(TiViewProxy.java:507)
09-26 14:31:01.984: E/AndroidRuntime(29249):    at org.appcelerator.titanium.proxy.TiViewProxy.handleGetView(TiViewProxy.java:491)
09-26 14:31:01.984: E/AndroidRuntime(29249):    at org.appcelerator.titanium.proxy.TiViewProxy.getOrCreateView(TiViewProxy.java:469)
09-26 14:31:01.984: E/AndroidRuntime(29249):    at org.appcelerator.titanium.proxy.TiViewProxy.handleAdd(TiViewProxy.java:670)
09-26 14:31:01.984: E/AndroidRuntime(29249):    at org.appcelerator.titanium.proxy.TiViewProxy.add(TiViewProxy.java:564)
09-26 14:31:01.984: E/AndroidRuntime(29249):    at ti.modules.titanium.ui.WindowProxy.windowCreated(WindowProxy.java:233)
09-26 14:31:01.984: E/AndroidRuntime(29249):    at org.appcelerator.titanium.TiActivityWindows.windowCreated(TiActivityWindows.java:32)
09-26 14:31:01.984: E/AndroidRuntime(29249):    at org.appcelerator.titanium.TiBaseActivity.windowCreated(TiBaseActivity.java:443)
09-26 14:31:01.984: E/AndroidRuntime(29249):    at org.appcelerator.titanium.TiBaseActivity.onCreate(TiBaseActivity.java:519)
09-26 14:31:01.984: E/AndroidRuntime(29249):    at org.appcelerator.titanium.TiActivity.onCreate(TiActivity.java:18)
09-26 14:31:01.984: E/AndroidRuntime(29249):    at android.app.Activity.performCreate(Activity.java:5231)
09-26 14:31:01.984: E/AndroidRuntime(29249):    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087)
09-26 14:31:01.984: E/AndroidRuntime(29249):    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2148)
09-26 14:31:01.984: E/AndroidRuntime(29249):    ... 12 more
```

**Comment by timanrebel** [comment]
Indeed, that one, was just about to post it

**Comment by manumaticx** [comment]
I think i fixed this. Hopefully I didn't break something because I also fooled around with the content fragment. If you like you can test it with version [1.1.8](https://github.com/manumaticx/Ti.DrawerLayout/blob/master/dist/com.tripvi.drawerlayout-android-1.1.8.zip)

**Comment by timanrebel** [comment]
Yes, you fixed it! Thanks!

**Comment by timanrebel** [comment]
One more thing: If I come back in the app after I have switched languages, the first title I have set is displayed in the actionable, not the latest title. In most cases that is the name of the top menu item. If I switch menu items, change language of Android, come back, the title of the first item is set again. I have tested it by setting a random string as the actionbar title. In that case the random string is displayed

@manumaticx My knowledge of Android is not good enough to fix this.. Any ideas?

**Comment by manumaticx** [comment]
Hi Timan,

you are changing the actionbar title (with an internationalized value) corresponding to your navigation menu but it gets reset to the initial value after changing the language? Do you happen to have a little example that I can reproduce this?

**Comment by timanrebel** [comment]
Let me create a Gist today with test case. Should have done that right away :)

**Comment by jeffkanazi** [comment]
Hi,

Is there a problem with the latest code? I used to get drawerclose events on both left and right drawer close but with 1.1.8 there is no longer drawerclose event fired for the right drawer. 

Any suggestions on to where to check for this in the code?
